In [2]:
import pandas as pd

In [3]:
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

In [4]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [12]:
data = pd.merge(ratings, movies, on = 'movieId')

In [13]:
user_counts = data['userId'].value_counts()

In [14]:
data = data[data['userId'].isin(user_counts[user_counts > 50].index)]

In [15]:
movie_counts = data['title'].value_counts()

In [16]:
data = data[data['title'].isin(movie_counts[movie_counts > 50].index)]

In [17]:
user_movie = data.pivot_table(index='userId', columns='title', values='rating')

In [18]:
user_movie = user_movie.fillna(0)

In [19]:
user_movie = (user_movie >= 3).astype(bool)

In [20]:
from mlxtend.frequent_patterns import apriori

In [22]:
from mlxtend.frequent_patterns import fpgrowth

In [ ]:
frequent_items = fpgrowth(user_movie, min_support=0.02, use_colnames=True)